#!/usr/bin/env python3
"""Write the block-out leaf atlas BobFoliage instances on branch tips (docs/FOLIAGE.md).

    uv run --project tools python tools/scripts/make_leaf_atlas.py

The point of shipping a placeholder is that the card recipe does not block on ComfyUI: it needs an
atlas with REAL cutout alpha to be testable at all, and a generated atlas replaces the picture, not
the plumbing. So this writes the smallest thing that exercises every property the real atlas has:

- a grid of cells (2x2), because the card picks a cell from a random index and a one-cell atlas
  would let a broken pick pass,
- straight alpha with a genuine cutout (most of each cell is transparent), because opaque leaves
  are the exact failure the redwood run measured and the reason cards exist,
- each spray growing from the BOTTOM edge of its cell, because a card's UV has v=0 at the
  attachment point and v=1 at the free tip, so a spray drawn centred would float off its twig,
- four visibly different sprays, so "the cell pick does nothing" is visible rather than plausible.

It is checked in (the pack has to work with no tools installed) and regenerated by re-running this;
it is deterministic, so a re-run with no edits produces the same bytes.
"""

from __future__ import annotations

import argparse
import math
import pathlib

import numpy as np
from PIL import Image

REPO = pathlib.Path(__file__).resolve().parents[2]
PACK = REPO / "blender" / "extensions" / "bob_blender_tools" / "assets"
SET_NAME = "leaf_atlas_blockout"

CELLS = 2          # 2x2. The recipe takes the grid as a param; the generated atlas sets the real one.
CELL_PX = 256

# Per-cell spray shape: (leaflet count, fan half-angle in degrees, leaflet length as a fraction of
# the cell, leaflet width, tint). Four distinct silhouettes so a stuck cell index is visible.
_SPRAYS = (
    (9, 62.0, 0.80, 0.055, (0.28, 0.44, 0.19)),
    (7, 38.0, 0.90, 0.075, (0.34, 0.50, 0.22)),
    (13, 78.0, 0.66, 0.040, (0.22, 0.38, 0.17)),
    (5, 24.0, 0.94, 0.105, (0.40, 0.55, 0.26)),
)


def _leaflet(alpha, tint, rgb, x0, y0, x1, y1, width, colour):
    """Draw one soft-edged leaflet: a lens along the segment (x0,y0)-(x1,y1), tapering to a point
    at both ends. Coordinates are in 0..1 cell space with y=0 at the base edge."""
    n = alpha.shape[0]
    ys, xs = np.mgrid[0:n, 0:n]
    px, py = (xs + 0.5) / n, (ys + 0.5) / n
    dx, dy = x1 - x0, y1 - y0
    length2 = dx * dx + dy * dy
    if length2 <= 0.0:
        return
    # Projection of each pixel onto the segment, clamped to it, then distance to that point.
    t = np.clip(((px - x0) * dx + (py - y0) * dy) / length2, 0.0, 1.0)
    dist = np.hypot(px - (x0 + t * dx), py - (y0 + t * dy))
    # Width tapers to zero at both ends, so the leaflet is a lens rather than a capsule.
    half = width * np.sin(np.pi * t) ** 0.6
    with np.errstate(divide="ignore", invalid="ignore"):
        cover = np.clip(1.0 - dist / np.maximum(half, 1e-6), 0.0, 1.0)
    cover = np.clip(cover * 2.2, 0.0, 1.0)  # a firm edge; the softness is a pixel or two of AA
    fresh = cover > alpha
    alpha[:] = np.maximum(alpha, cover)
    for c in range(3):
        rgb[:, :, c] = np.where(fresh, colour[c] * (0.72 + 0.28 * cover), rgb[:, :, c])
    tint[:] = np.maximum(tint, cover)


def _cell(index):
    """One atlas cell as (rgb, alpha), both float 0..1, y=0 at the base edge."""
    count, fan, reach, width, colour = _SPRAYS[index % len(_SPRAYS)]
    alpha = np.zeros((CELL_PX, CELL_PX), dtype=np.float32)
    tint = np.zeros((CELL_PX, CELL_PX), dtype=np.float32)
    rgb = np.zeros((CELL_PX, CELL_PX, 3), dtype=np.float32)

    # The stem: a thin dark leaflet up the middle, so the spray is attached to something.
    _leaflet(alpha, tint, rgb, 0.5, 0.0, 0.5, reach * 0.96, 0.016,
             (colour[0] * 0.55, colour[1] * 0.5, colour[2] * 0.5))
    for i in range(count):
        # Walk up the stem, alternating sides, shortening toward the tip.
        along = 0.10 + 0.82 * (i / max(1, count - 1))
        side = 1.0 if i % 2 == 0 else -1.0
        angle = math.radians(fan) * side * (0.55 + 0.45 * (1.0 - along))
        span = reach * (0.52 - 0.34 * along)
        base_x, base_y = 0.5, along * reach * 0.94
        shade = 0.82 + 0.18 * ((i * 7) % 5) / 4.0
        _leaflet(alpha, tint, rgb, base_x, base_y,
                 base_x + math.sin(angle) * span, base_y + math.cos(angle) * span * 0.75,
                 width, tuple(c * shade for c in colour))
    return rgb, alpha


def build():
    """The whole atlas as a HxWx4 uint8 array in PNG row order (row 0 = top)."""
    size = CELLS * CELL_PX
    out = np.zeros((size, size, 4), dtype=np.float32)
    for row in range(CELLS):
        for col in range(CELLS):
            rgb, alpha = _cell(row * CELLS + col)
            # UV v=0 is the BOTTOM of the image, so cell row 0 lands on the bottom band and each
            # cell's own y=0 (the spray's base) lands on that band's lower edge.
            y0 = size - (row + 1) * CELL_PX
            x0 = col * CELL_PX
            block = out[y0:y0 + CELL_PX, x0:x0 + CELL_PX]
            block[:, :, :3] = rgb[::-1]
            block[:, :, 3] = alpha[::-1]
    return (np.clip(out, 0.0, 1.0) * 255.0 + 0.5).astype(np.uint8)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default="", help="target folder (default: the bundled block-out pack)")
    args = ap.parse_args(argv)

    base = pathlib.Path(args.out) if args.out else PACK / "textures" / SET_NAME
    base.mkdir(parents=True, exist_ok=True)
    path = base / f"{SET_NAME}_basecolor.png"
    Image.fromarray(build(), mode="RGBA").save(path, optimize=True)
    covered = np.count_nonzero(build()[:, :, 3] > 127) / float(build()[:, :, 3].size)
    print(f"wrote {path} ({CELLS}x{CELLS} cells, {covered * 100:.1f}% opaque)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
